# Generated by Django 3.1.2 on 2020-11-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.restaurant'),
        ),
    ]
