# Generated by Django 3.1.2 on 2020-11-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_manager_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='address',
        ),
    ]
