# Generated by Django 3.1.2 on 2020-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_guest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
