# Generated by Django 3.1.2 on 2020-11-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_manager_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_manager',
        ),
    ]
