# Generated by Django 3.1.2 on 2020-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_url',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profile_img',
            field=models.BinaryField(),
        ),
    ]
