# Generated by Django 3.1.2 on 2020-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201120_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='profile_img',
            field=models.FileField(upload_to=''),
        ),
    ]
