# Generated by Django 3.1.2 on 2020-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201120_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.TextField(default=False),
        ),
    ]
