# Generated by Django 3.1.2 on 2020-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201120_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
