# Generated by Django 3.1.2 on 2020-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201121_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
